server:
  port: 8072
spring:
  application:
    name: "gatewayserver"
  config:
    import:  "${SPRING_CONFIG_IMPORT:optional:configserver:http://localhost:8071}"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway: true
  info:
    env:
      enabled: true


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "${EUREKA_SERVER_URL:http://localhost:8070/eureka}"

endpoint:
  shutdown:
    enabled: true


info:
  app:
    name: "gatewayserver"
    description: "Gateway server Application"
    version: "1.0"

logging:
  level:
    com.vishnu.accounts.service.clients.LoansFeignClient: DEBUG