deploymentName: accounts-deployment
serviceName: accounts
appLabel: accounts
appName: accounts

replicaCount: 1

image:
  repository: eazybytes/accounts
  tag: "1.0"

containerPort: 8080

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
rabbitmq_enabled: true