deploymentName: message-deployment
serviceName: message
appLabel: message
appName: message

replicaCount: 1

image:
  repository: eazybytes/message
  tag: "1.0"

containerPort: 9010

service:
  type: LoadBalancer
  port: 9010
  targetPort: 9010

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: false
resouceserver_enabled: false
rabbitmq_enabled: true