global:
  configMapName: eazybankdev-configmap
  activeProfile: default
  configServerURL: configserver:http://configserver:8071/
  eurekaServerURL: http://eurekaserver:8070/eureka/
  keyCloakURL: http://keycloak-headless.default.svc.cluster.local:8080
  rabbitmqHost: rabbitmq.default.svc.cluster.local
  discoveryServerUrl: "http://spring-cloud-kubernetes-discoveryserver:80/"