deploymentName: cards-deployment
serviceName: cards
appLabel: cards
appName: cards

replicaCount: 1

image:
  repository: zorozephyr/cards
  tag: "2.0"

containerPort: 8080

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

appname_enabled: true
profile_enabled: true
config_enabled: true
disovery_enabled: true
eureka_enabled: true
resouceserver_enabled: false
rabbitmq_enabled: true
