deploymentName: loans-deployment
serviceName: loans
appLabel: loans
appName: loans

replicaCount: 1

image:
  repository: eazybytes/loans
  tag: "2.0"

containerPort: 8090

service:
  type: LoadBalancer
  port: 8090
  targetPort: 8090

appname_enabled: true
profile_enabled: true
config_enabled: true
disovery_enabled: true
eureka_enabled: true
resouceserver_enabled: false
rabbitmq_enabled: false